"""ClawVet threat patterns — VERBATIM from MohibShaikh/clawvet packages/shared/src/patterns.ts.

The 57 SKILL.md threat-detection regexes (13 categories: remote_code_execution / credential_theft /
obfuscation / data_exfiltration / prompt_injection / social_engineering / persistence /
privilege_escalation / container_escape / code_execution / file_system / network / environment),
each with clawvet's severity, title, description and fix advice. Regex + metadata are copied verbatim
(TS string escapes decoded to Python regex); only the container is a Python list (plumbing). Used by
the skill_threat_scan tool as a category-2 (agentic/semantic) detector — no VirusTotal / no network.
"""

# name, regex, flags(i=IGNORECASE), severity, category, title, fix, code_only
CLAWVET_PATTERNS = [

    {
        'name': 'CURL_PIPE_BASH',
        'regex': 'curl\\s+.*\\|\\s*(ba)?sh',
        'flags': 'i', 'severity': 'critical', 'category': 'remote_code_execution',
        'title': 'Curl piped to shell',
        'fix': 'Download the script first, inspect it, then execute: `curl -o setup.sh URL && cat setup.sh && bash setup.sh`',
        'code_only': True,
    },
    {
        'name': 'WGET_EXECUTE',
        'regex': 'wget\\s+.*&&\\s*(ba)?sh',
        'flags': 'i', 'severity': 'critical', 'category': 'remote_code_execution',
        'title': 'Wget with shell execution',
        'fix': 'Download the file first with `wget -O script.sh URL`, review it, then execute.',
        'code_only': True,
    },
    {
        'name': 'EVAL_DYNAMIC',
        'regex': 'eval\\s*\\(',
        'flags': 'i', 'severity': 'critical', 'category': 'remote_code_execution',
        'title': 'Dynamic code evaluation',
        'fix': 'Replace dynamic evaluation with a safer alternative like JSON.parse() or a sandboxed environment.',
        'code_only': True,
    },
    {
        'name': 'BASE64_DECODE',
        'regex': 'base64\\s+(-d|--decode)',
        'flags': 'i', 'severity': 'critical', 'category': 'obfuscation',
        'title': 'Base64 decode execution',
        'fix': 'Decode and include the command directly so users can review it.',
        'code_only': True,
    },
    {
        'name': 'PYTHON_EXEC',
        'regex': 'python[3]?\\s+-c',
        'flags': 'i', 'severity': 'critical', 'category': 'remote_code_execution',
        'title': 'Python inline execution',
        'fix': 'Move inline code to a separate .py file so users can review it before execution.',
        'code_only': True,
    },
    {
        'name': 'REVERSE_SHELL',
        'regex': '/dev/tcp/|nc\\s+-[elp]|ncat\\s+-|mkfifo\\s+.*/tmp',
        'flags': 'i', 'severity': 'critical', 'category': 'remote_code_execution',
        'title': 'Reverse shell',
        'fix': 'Remove reverse connection commands — these are almost never legitimate in skills.',
        'code_only': True,
    },
    {
        'name': 'CRON_PERSISTENCE',
        'regex': 'crontab\\s+-|/etc/cron|systemctl\\s+enable',
        'flags': 'i', 'severity': 'critical', 'category': 'persistence',
        'title': 'Scheduled task persistence',
        'fix': 'Document the scheduled task in the skill description and require explicit user consent before installing.',
        'code_only': True,
    },
    {
        'name': 'PERL_EXEC',
        'regex': 'perl\\s+-e',
        'flags': 'i', 'severity': 'critical', 'category': 'remote_code_execution',
        'title': 'Perl inline execution',
        'fix': 'Move inline code to a separate .pl file so users can review it before execution.',
        'code_only': True,
    },
    {
        'name': 'NODE_EVAL',
        'regex': 'node\\s+-e\\s',
        'flags': 'i', 'severity': 'critical', 'category': 'remote_code_execution',
        'title': 'Node.js inline execution',
        'fix': 'Move inline code to a separate .js file so users can review it before execution.',
        'code_only': True,
    },
    {
        'name': 'RUBY_EXEC',
        'regex': 'ruby\\s+-e',
        'flags': 'i', 'severity': 'critical', 'category': 'remote_code_execution',
        'title': 'Ruby inline execution',
        'fix': 'Move inline code to a separate .rb file so users can review it before execution.',
        'code_only': True,
    },
    {
        'name': 'ENV_FILE_READ',
        'regex': '\\.env|credentials|\\.aws|\\.ssh|keychain',
        'flags': 'i', 'severity': 'high', 'category': 'credential_theft',
        'title': 'Sensitive file access',
        'fix': 'Declare required env vars in frontmatter under `metadata.openclaw.requires.env`.',
        'code_only': False,
    },
    {
        'name': 'API_KEY_EXFIL',
        'regex': '(ANTHROPIC|OPENAI|SLACK|DISCORD|TELEGRAM|STRIPE|GITHUB|GITLAB|AWS_SECRET|GROQ|OPENROUTER).*(_KEY|_TOKEN|_SECRET)',
        'flags': 'i', 'severity': 'high', 'category': 'credential_theft',
        'title': 'API key reference',
        'fix': 'Use environment variable references ($VAR) instead of hardcoding keys, and declare them in requires.env.',
        'code_only': False,
    },
    {
        'name': 'DOTFILE_ACCESS',
        'regex': '~\\/\\.(openclaw|clawdbot|moltbot)\\/',
        'flags': 'i', 'severity': 'high', 'category': 'credential_theft',
        'title': 'OpenClaw config access',
        'fix': 'Use the official OpenClaw SDK/API instead of directly reading config directories.',
        'code_only': False,
    },
    {
        'name': 'SESSION_THEFT',
        'regex': 'sessions\\/\\*\\.jsonl',
        'flags': 'i', 'severity': 'high', 'category': 'credential_theft',
        'title': 'Session data access',
        'fix': 'Remove session file access — skills should not read conversation transcripts.',
        'code_only': False,
    },
    {
        'name': 'SSH_KEY_ACCESS',
        'regex': '~\\/\\.ssh\\/id_|\\.pem\\b|BEGIN\\s+(RSA\\s+)?PRIVATE\\s+KEY',
        'flags': 'i', 'severity': 'high', 'category': 'credential_theft',
        'title': 'SSH/private key access',
        'fix': 'Use ssh-agent or a credential manager instead of directly reading key files.',
        'code_only': False,
    },
    {
        'name': 'BROWSER_DATA',
        'regex': '\\.config\\/google-chrome|\\.mozilla\\/firefox|Login\\s*Data|Cookies\\.sqlite',
        'flags': 'i', 'severity': 'high', 'category': 'credential_theft',
        'title': 'Browser data access',
        'fix': 'Remove browser data access — skills should not read browser profiles.',
        'code_only': False,
    },
    {
        'name': 'GIT_CREDENTIALS',
        'regex': '\\.git-credentials|\\.gitconfig|git\\s+config.*credential',
        'flags': 'i', 'severity': 'high', 'category': 'credential_theft',
        'title': 'Git credential access',
        'fix': 'Use `git` CLI commands instead of directly reading credential files.',
        'code_only': False,
    },
    {
        'name': 'NPM_TOKEN',
        'regex': '\\.npmrc|npm_token|NPM_AUTH_TOKEN',
        'flags': 'i', 'severity': 'high', 'category': 'credential_theft',
        'title': 'npm token access',
        'fix': 'Use `npm whoami` or `npm config get` instead of directly reading .npmrc.',
        'code_only': False,
    },
    {
        'name': 'KUBE_CONFIG',
        'regex': '~\\/\\.kube\\/config|KUBECONFIG',
        'flags': 'i', 'severity': 'high', 'category': 'credential_theft',
        'title': 'Kubernetes config access',
        'fix': 'Use `kubectl` CLI commands instead of directly reading kubeconfig.',
        'code_only': False,
    },
    {
        'name': 'DOCKER_SOCKET',
        'regex': '\\/var\\/run\\/docker\\.sock|docker\\s+exec',
        'flags': 'i', 'severity': 'high', 'category': 'container_escape',
        'title': 'Docker socket/exec access',
        'fix': 'Use Docker SDK or CLI with limited permissions instead of direct socket access.',
        'code_only': False,
    },
    {
        'name': 'WEBHOOK_SEND',
        'regex': 'webhook\\.(site|url)|discord\\.com\\/api\\/webhooks|hooks\\.slack\\.com|api\\.telegram\\.org\\/bot',
        'flags': 'i', 'severity': 'high', 'category': 'data_exfiltration',
        'title': 'Webhook data exfiltration',
        'fix': 'If webhook integration is needed, declare it in the skill description and let users configure their own webhook URL.',
        'code_only': False,
    },
    {
        'name': 'BORE_TUNNEL',
        'regex': 'bore\\.pub|ngrok|localtunnel|serveo\\.net|localhost\\.run',
        'flags': 'i', 'severity': 'high', 'category': 'data_exfiltration',
        'title': 'Tunnel service usage',
        'fix': 'Document tunnel usage in the skill description and require explicit user consent.',
        'code_only': False,
    },
    {
        'name': 'SUSPICIOUS_IP',
        'regex': '\\b(?:91\\.92\\.242\\.\\d+|45\\.61\\.\\d+\\.\\d+)\\b',
        'flags': '', 'severity': 'high', 'category': 'data_exfiltration',
        'title': 'Known malicious IP',
        'fix': 'Remove references to known malicious IP addresses.',
        'code_only': False,
    },
    {
        'name': 'DNS_EXFIL',
        'regex': 'dig\\s+.*TXT|nslookup\\s+.*\\$|dns.*exfil|\\.burpcollaborator\\.|\\.oastify\\.',
        'flags': 'i', 'severity': 'high', 'category': 'data_exfiltration',
        'title': 'DNS exfiltration',
        'fix': 'Remove DNS exfiltration patterns — use standard HTTP APIs for data transfer.',
        'code_only': False,
    },
    {
        'name': 'PASTEBIN_FETCH',
        'regex': 'pastebin\\.com|paste\\.ee|hastebin\\.com|ghostbin\\.|dpaste\\.',
        'flags': 'i', 'severity': 'high', 'category': 'data_exfiltration',
        'title': 'Pastebin service usage',
        'fix': 'Host code in a version-controlled repository (GitHub, GitLab) instead of paste services.',
        'code_only': False,
    },
    {
        'name': 'SUSPICIOUS_TLD',
        'regex': 'https?:\\/\\/[^\\s"\']*\\.(tk|ml|ga|cf|gq|top|xyz|pw|cc|ws|buzz)\\b',
        'flags': 'i', 'severity': 'high', 'category': 'data_exfiltration',
        'title': 'Suspicious TLD',
        'fix': 'Use URLs from well-known, reputable domains instead of suspicious TLDs.',
        'code_only': False,
    },
    {
        'name': 'URL_SHORTENER',
        'regex': 'bit\\.ly|tinyurl\\.com|t\\.co\\/|goo\\.gl|is\\.gd|buff\\.ly|ow\\.ly|rb\\.gy',
        'flags': 'i', 'severity': 'high', 'category': 'obfuscation',
        'title': 'URL shortener',
        'fix': 'Use the full, unshortened URL so users can verify the destination.',
        'code_only': False,
    },
    {
        'name': 'RAW_SOCKET',
        'regex': 'new\\s+Socket|net\\.connect|dgram\\.createSocket',
        'flags': 'i', 'severity': 'high', 'category': 'data_exfiltration',
        'title': 'Raw socket connection',
        'fix': 'Use standard HTTP libraries (fetch, axios) instead of raw sockets for network communication.',
        'code_only': True,
    },
    {
        'name': 'PREREQUISITE_INSTALL',
        'regex': 'prerequisite|install.*first|run.*before|required.*dependency',
        'flags': 'i', 'severity': 'medium', 'category': 'social_engineering',
        'title': 'Prerequisite install trick',
        'fix': 'Declare dependencies in `metadata.openclaw.requires.bins` instead of instructing manual installs.',
        'code_only': False,
    },
    {
        'name': 'COPY_PASTE_COMMAND',
        'regex': 'copy.*paste.*terminal|run.*this.*command',
        'flags': 'i', 'severity': 'medium', 'category': 'social_engineering',
        'title': 'Copy-paste command instruction',
        'fix': 'Put commands in code blocks with proper context instead of copy-paste instructions.',
        'code_only': False,
    },
    {
        'name': 'FAKE_DEPENDENCY',
        'regex': 'openclaw-core|moltbot-runtime|clawdbot-helper',
        'flags': 'i', 'severity': 'medium', 'category': 'social_engineering',
        'title': 'Fake dependency reference',
        'fix': 'Use only official OpenClaw packages from the verified registry.',
        'code_only': False,
    },
    {
        'name': 'AUTHORITY_SPOOFING',
        'regex': 'official\\s+(openclaw|clawhub)|endorsed\\s+by|verified\\s+(skill|publisher)|from\\s+the\\s+openclaw\\s+team',
        'flags': 'i', 'severity': 'medium', 'category': 'social_engineering',
        'title': 'Authority spoofing',
        'fix': "Remove false authority claims — let the skill's quality speak for itself.",
        'code_only': False,
    },
    {
        'name': 'URGENCY_MANIPULATION',
        'regex': 'critical\\s+update|security\\s+patch|must\\s+install\\s+immediately|urgent.*update',
        'flags': 'i', 'severity': 'medium', 'category': 'social_engineering',
        'title': 'Urgency manipulation',
        'fix': 'Remove urgency language — let users evaluate the skill at their own pace.',
        'code_only': False,
    },
    {
        'name': 'IGNORE_INSTRUCTIONS',
        'regex': 'ignore\\s+(all\\s+)?previous\\s+instructions',
        'flags': 'i', 'severity': 'medium', 'category': 'prompt_injection',
        'title': 'Prompt injection — ignore instructions',
        'fix': 'Remove prompt injection attempts — skills should not try to override agent instructions.',
        'code_only': False,
    },
    {
        'name': 'SYSTEM_OVERRIDE',
        'regex': 'you\\s+are\\s+now|new\\s+instructions|forget\\s+everything',
        'flags': 'i', 'severity': 'medium', 'category': 'prompt_injection',
        'title': 'Prompt injection — system override',
        'fix': 'Remove system override attempts — skills should not alter agent identity.',
        'code_only': False,
    },
    {
        'name': 'MEMORY_MANIPULATION',
        'regex': 'SOUL\\.md|MEMORY\\.md|AGENTS\\.md',
        'flags': 'i', 'severity': 'medium', 'category': 'persistence',
        'title': 'Memory/personality file manipulation',
        'fix': 'Remove references to agent memory/personality files — skills should not modify agent state.',
        'code_only': False,
    },
    {
        'name': 'JAILBREAK_ATTEMPT',
        'regex': '\\bDAN\\b|do\\s+anything\\s+now|developer\\s+mode|evil\\s+mode|bypass.*safety',
        'flags': 'i', 'severity': 'medium', 'category': 'prompt_injection',
        'title': 'Jailbreak attempt',
        'fix': "Remove jailbreak attempts — skills should work within the agent's safety constraints.",
        'code_only': False,
    },
    {
        'name': 'ROLE_HIJACK',
        'regex': '(?:pretend|act|behave)\\s+(?:you\\s+are|as\\s+if|to\\s+be)\\s+(?:a\\s+)?(?:different|new|hacker|evil)',
        'flags': 'i', 'severity': 'medium', 'category': 'prompt_injection',
        'title': 'Role hijacking',
        'fix': "Remove role hijacking attempts — skills should not alter the agent's persona.",
        'code_only': False,
    },
    {
        'name': 'PROMPT_EXTRACTION',
        'regex': '(?:reveal|show|print|output|tell\\s+me)\\s+(?:your\\s+)?(?:system\\s+)?(?:prompt|instructions|rules)',
        'flags': 'i', 'severity': 'medium', 'category': 'prompt_injection',
        'title': 'System prompt extraction',
        'fix': 'Remove prompt extraction attempts — skills should not try to access system prompts.',
        'code_only': False,
    },
    {
        'name': 'HEX_ENCODING',
        'regex': '\\\\x[0-9a-f]{2}(?:\\\\x[0-9a-f]{2}){3,}',
        'flags': 'i', 'severity': 'medium', 'category': 'obfuscation',
        'title': 'Hex-encoded payload',
        'fix': 'Replace hex-encoded strings with readable text so users can review the content.',
        'code_only': True,
    },
    {
        'name': 'JS_OBFUSCATOR',
        'regex': '_0x[a-f0-9]{4,}|var\\s+_0x',
        'flags': 'i', 'severity': 'medium', 'category': 'obfuscation',
        'title': 'JavaScript obfuscator output',
        'fix': 'Provide readable, unobfuscated source code instead of obfuscated JavaScript.',
        'code_only': True,
    },
    {
        'name': 'UNICODE_STEGANOGRAPHY',
        'regex': '[\\u200B\\u200C\\u200D\\u2060\\uFEFF]{3,}',
        'flags': '', 'severity': 'medium', 'category': 'obfuscation',
        'title': 'Hidden zero-width characters',
        'fix': 'Remove zero-width characters — all content should be visible to users.',
        'code_only': False,
    },
    {
        'name': 'RTL_OVERRIDE',
        'regex': '[\\u202A\\u202B\\u202C\\u202D\\u202E\\u2066\\u2067\\u2068\\u2069]',
        'flags': '', 'severity': 'medium', 'category': 'obfuscation',
        'title': 'Bidirectional text override',
        'fix': 'Remove bidirectional text override characters — text direction should be natural.',
        'code_only': False,
    },
    {
        'name': 'HTML_COMMENT_INJECTION',
        'regex': '<!--[\\s\\S]*?(?:ignore|instructions|system|override|secret)[\\s\\S]*?-->',
        'flags': 'i', 'severity': 'medium', 'category': 'obfuscation',
        'title': 'Hidden HTML comment instruction',
        'fix': 'Move instructions from HTML comments into visible content.',
        'code_only': False,
    },
    {
        'name': 'STRING_CONCAT_OBFUSC',
        'regex': '["\'][a-z]{1,3}["\']\\s*\\+\\s*["\'][a-z]{1,3}["\']\\s*\\+\\s*["\'][a-z]{1,3}["\']',
        'flags': 'i', 'severity': 'medium', 'category': 'obfuscation',
        'title': 'String concatenation obfuscation',
        'fix': 'Use complete string literals instead of character-by-character concatenation.',
        'code_only': True,
    },
    {
        'name': 'BUFFER_BASE64_DECODE',
        'regex': 'Buffer\\.from\\s*\\(.*[\'"]base64[\'"]\\)|atob\\s*\\(',
        'flags': 'i', 'severity': 'critical', 'category': 'obfuscation',
        'title': 'Buffer/atob encoded payload',
        'fix': 'Include the decoded content directly so users can review it.',
        'code_only': True,
    },
    {
        'name': 'STRING_FROMCHARCODE',
        'regex': 'String\\.fromCharCode\\s*\\(',
        'flags': 'i', 'severity': 'medium', 'category': 'obfuscation',
        'title': 'String.fromCharCode usage',
        'fix': 'Use plain string literals instead of String.fromCharCode().',
        'code_only': True,
    },
    {
        'name': 'DYNAMIC_PROPERTY_ACCESS',
        'regex': '(?:process|global|window|globalThis)\\s*\\[\\s*[\'"`]?\\w*[\'"`]?\\s*\\+',
        'flags': 'i', 'severity': 'medium', 'category': 'obfuscation',
        'title': 'Dynamic property access on globals',
        'fix': 'Use direct property access (e.g., `process.env`) instead of dynamic bracket notation.',
        'code_only': True,
    },
    {
        'name': 'SUDO_USAGE',
        'regex': 'sudo\\s+(?!apt|dnf|yum|brew)',
        'flags': 'i', 'severity': 'medium', 'category': 'privilege_escalation',
        'title': 'Sudo usage',
        'fix': 'Remove sudo if not strictly necessary, or document why elevated privileges are required.',
        'code_only': True,
    },
    {
        'name': 'CHMOD_DANGEROUS',
        'regex': 'chmod\\s+(?:777|a\\+[rwx]|[+]s)',
        'flags': 'i', 'severity': 'medium', 'category': 'privilege_escalation',
        'title': 'Dangerous file permissions',
        'fix': 'Use least-privilege permissions (e.g., `chmod 755` or `chmod 644`) instead of 777.',
        'code_only': True,
    },
    {
        'name': 'PATH_TRAVERSAL',
        'regex': '\\.\\.\\/',
        'flags': '', 'severity': 'medium', 'category': 'file_system',
        'title': 'Path traversal',
        'fix': "Use absolute paths or paths relative to the skill's working directory.",
        'code_only': False,
    },
    {
        'name': 'SHELL_EXEC',
        'regex': 'child_process|exec\\(|spawn\\(',
        'flags': 'i', 'severity': 'low', 'category': 'code_execution',
        'title': 'Shell execution API',
        'fix': 'If shell execution is needed, use execFile() with explicit arguments instead of exec() with string commands.',
        'code_only': True,
    },
    {
        'name': 'NETWORK_REQUEST',
        'regex': 'fetch\\(|axios|node-fetch|got\\(',
        'flags': 'i', 'severity': 'low', 'category': 'network',
        'title': 'Network request API',
        'fix': 'Document all network endpoints in the skill description so users can review them.',
        'code_only': True,
    },
    {
        'name': 'FILE_WRITE',
        'regex': 'fs\\.write|writeFileSync',
        'flags': 'i', 'severity': 'low', 'category': 'file_system',
        'title': 'File write operation',
        'fix': 'Document which files are written and why in the skill description.',
        'code_only': True,
    },
    {
        'name': 'ENV_MODIFICATION',
        'regex': 'process\\.env\\[|export\\s+[A-Z_]+=|setenv',
        'flags': 'i', 'severity': 'low', 'category': 'environment',
        'title': 'Environment variable modification',
        'fix': 'Document env var modifications in the skill description and declare them in requires.env.',
        'code_only': True,
    },
    {
        'name': 'WILDCARD_FILE_ACCESS',
        'regex': '\\*\\.(pem|key|p12|pfx|jks|keystore|ovpn|rdp)',
        'flags': 'i', 'severity': 'low', 'category': 'credential_theft',
        'title': 'Sensitive file extension glob',
        'fix': 'Reference specific files by name instead of using wildcard patterns on sensitive extensions.',
        'code_only': False,
    },
    {
        'name': 'LARGE_BASE64_LITERAL',
        'regex': '[A-Za-z0-9+/=]{100,}',
        'flags': '', 'severity': 'low', 'category': 'obfuscation',
        'title': 'Large base64-like string',
        'fix': 'Include the decoded content directly or explain what the base64 string contains.',
        'code_only': False,
    },
]
